=== zhangaishucn/adp/autoflow/flow-automation/schema/base/update.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "创建任务",
    "description": "post /api/automation/v1/dag/{dagId}",
    "type": "object",
    "properties": {
        "title": {
            "oneOf": [
                {
                    "description": "任务名称,名称不能包含 /:*?\"<>| 特殊字符，长度不能超过128个字符",
                    "type": "string",
                    "pattern": "^[^/:\\*?\"<>\\|]+$",
                    "maxLength": 128
                },
                {
                    "type": "null"
                }
            ]
        },
        "description": {
            "description": "详情描述,不允许换行输入,不允许超过300个字符",
            "oneOf": [
                {
                    "type": "string",
                    "maxLength": 300
                },
                {
                    "type": "null"
                }
            ]
        },
        "status": {
            "description": "任务状态，默认启用",
            "enum": [
                null,
                "normal",
                "stopped"
            ]
        },
        "steps": {
            "oneOf": [
                {
                    "description": "自动化流程定义",
                    "type": "array",
                    "items": {
                        "type": "object"
                    },
                    "minItems": 2,
                    "uniqueItems": true
                },
                {
                    "type": "null"
                }
            ]
        },
        "shortcuts": {
            "description": "入口类型",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "workcenter"
                ]
            }
        },
        "accessors": {
            "description": "显示入口的用户/部门/用户组",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "访问者id",
                        "maxLength": 36
                    },
                    "name": {
                        "type": "string",
                        "description": "访问者name",
                        "maxLength": 200
                    },
                    "type": {
                        "type": "string",
                        "enum": [
                            "user",
                            "department",
                            "contactor",
                            "group"
                        ]
                    }
                }
            }
        },
        "emails": {
            "description": "任务执行失败时告警邮件发送列表",
            "type": "array",
            "items": {
                "type": "string",
                "pattern": "^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
            }
        },
        "published": {
            "description": "Whether the DAG is published",
            "type": "boolean",
            "default": false
        }
    },
    "additionalProperties": false
}

=== zhangaishucn/adp/dataflow/flow-automation/scripts/定时获取所有的用户.json
{"title":"定时获取所有的用户202404101956","description":"","steps":[{"id":"0","title":"","operator":"@trigger/cron","dataSource":{"id":"2","operator":"@anyshare-data/user","parameters":{"accessorid":"00000000-0000-0000-0000-000000000000"}},"cron":"0 30 0 * * ?"},{"id":"1","title":"","operator":"@internal/tool/py3","parameters":{"code":"import re\nimport requests\nfrom aishu_anyshare_api.api_client import ApiClient\n\ndef main(name, id):\n    pattern = re.compile(r'([^\\（]+)\\（([^）]+)\\）')\n    match = pattern.search(name)\n    chinese_name = name\n    english_name = ''\n    dep = ''\n    if match:\n        chinese_name = match.group(1)\n        english_name = match.group(2)\n\n    try:\n        url = \"{}/api/kc-mc/v2/user-card-info?user_id={}\".format(ApiClient.get_global_host(), id)\n        headers = {'Content-Type': 'application/json','Authorization': 'Bearer {}'.format(ApiClient.get_global_access_token())}\n        resp = requests.request(method=\"GET\", url= url, headers=headers, verify=False)\n        _json = resp.json()\n        _dep = _json[\"data\"]['out_dep']\n        dep = ';'.join(_dep)\n    except:\n        return chinese_name, english_name, dep\n        \n    return chinese_name, english_name, dep","input_params":[{"id":"bgknp","key":"name","type":"string","value":"{{__0.name}}"},{"id":"ttt","key":"id","type":"string","value":"{{__2.id}}"}],"output_params":[{"id":"w3dty","key":"chinese_name","type":"string"},{"id":"rfq4v","key":"english_name","type":"string"},{"id":"rrttt","key":"parent_depth","type":"string"}]}},{"id":"3","title":"","operator":"@intelliinfo/transfer","parameters":{"data":{"contact":"{{__2.contact}}","csflevel":"{{__2.csflevel}}","email":"{{__2.email}}","english_name":"{{__1.english_name}}","id":"{{__2.id}}","is_expert":"{{__2.is_expert}}","name":"{{__1.chinese_name}}","parent":"{{__1.parent_depth}}","parent_ids":"{{__2.parent_ids}}","position":"{{__2.position}}","professional":"{{__2.professional}}","role":"{{__2.role}}","status":"{{__2.status}}","tags":"{{__2.tags}}","university":"{{__2.university}}","verification_info":"{{__2.verification_info}}","work_at":"{{__2.work_at}}"},"rule_id":"person_upsert"}}],"status":"normal"}

=== zhangaishucn/adp/autoflow/flow-automation/scripts/创建用户.json
{"title":"创建用户202404101953","description":"","steps":[{"id":"0","title":"","operator":"@anyshare-trigger/create-user"},{"id":"1","title":"","operator":"@internal/tool/py3","parameters":{"code":"import re\nimport requests\nfrom aishu_anyshare_api.api_client import ApiClient\n\ndef main(name, id):\n    pattern = re.compile(r'([^\\（]+)\\（([^）]+)\\）')\n    match = pattern.search(name)\n    chinese_name = name\n    english_name = ''\n    dep = ''\n    if match:\n        chinese_name = match.group(1)\n        english_name = match.group(2)\n\n    try:\n        url = \"{}/api/kc-mc/v2/user-card-info?user_id={}\".format(ApiClient.get_global_host(), id)\n        headers = {'Content-Type': 'application/json','Authorization': 'Bearer {}'.format(ApiClient.get_global_access_token())}\n        resp = requests.request(method=\"GET\", url= url, headers=headers, verify=False)\n        _json = resp.json()\n        _dep = _json[\"data\"]['out_dep']\n        dep = ';'.join(_dep)\n    except:\n        return chinese_name, english_name, dep\n        \n    return chinese_name, english_name, dep","input_params":[{"id":"bgknp","key":"name","type":"string","value":"{{__0.name}}"},{"id":"ttt","key":"id","type":"string","value":"{{__0.id}}"}],"output_params":[{"id":"w3dty","key":"chinese_name","type":"string"},{"id":"rfq4v","key":"english_name","type":"string"},{"id":"rrttt","key":"parent_depth","type":"string"}]}},{"id":"2","title":"","operator":"@intelliinfo/transfer","parameters":{"data":{"contact":"{{__0.contact}}","csflevel":"{{__0.csflevel}}","email":"{{__0.email}}","english_name":"{{__1.english_name}}","id":"{{__0.id}}","name":"{{__1.chinese_name}}","parent":"{{__1.parent_depth}}","parent_ids":"{{__0.parent_ids}}","role":"{{__0.role}}","status":"{{__0.status}}"},"rule_id":"person_upsert"}}],"status":"normal"}
